name: custom_lints_test
description: A starting point for Dart libraries or applications.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0"
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.5.2
  custom_lints:
    path: custom_lints
