name: custom-lints-test

on:
  push:


jobs:
  check:
    name: "Run custom lints"
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages
        run: apt-get update && apt-get install -y jq curl xz-utils git

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: "Check"
        run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.13.0-x64
          flutter pub get
          flutter pub run custom_lint
