name: custom-lints-test

on:
  push:


jobs:
  check:
    name: "Run custom lints"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.10.6
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Check"
        run: |
          dart pub get
          dart pub run custom_lint
